# Generated by Django 5.2.17 on 2026-09-30 13:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, help_text='One line per line. Printed as written.')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('vat_registered', models.BooleanField(default=False, help_text='Off: documents are titled “Invoice” with no VAT line. On: “Tax Invoice”, with your VAT number and a VAT breakdown.')),
                ('vat_number', models.CharField(blank=True, max_length=30)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Percent. Only used when VAT is switched on.', max_digits=5)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('branch_code', models.CharField(blank=True, max_length=20)),
                ('account_holder', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('account_type', models.CharField(blank=True, max_length=40)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('default_payment_terms_days', models.PositiveSmallIntegerField(default=14, help_text='Due date offered on a new invoice, in days from the issue date.')),
                ('default_quote_validity_days', models.PositiveSmallIntegerField(default=30, help_text='How long a new quote stays open, in days.')),
                ('default_notes', models.TextField(blank=True, help_text='Pre-filled into the notes field on a new document.')),
                ('accent_colour', models.CharField(default='#8A3324', help_text='The single accent used on the PDF. Hex, e.g. #8A3324.', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'business settings',
                'verbose_name_plural': 'business settings',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(help_text='The customer or company name', max_length=200)),
                ('contact_person', models.CharField(blank=True, help_text='Printed as “Att:” on the document', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal. Never printed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('kind', models.CharField(choices=[('quote', 'Quote'), ('invoice', 'Invoice')], max_length=20, primary_key=True, serialize=False)),
                ('next_number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'number sequence',
                'verbose_name_plural': 'number sequences',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('quote', 'Quote'), ('invoice', 'Invoice')], default='invoice', max_length=10)),
                ('number', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('project', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Quotes only. After this date the quote is expired.', null=True)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('adjustment_label', models.CharField(blank=True, help_text='e.g. “Returning client discount”', max_length=120)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Negative for a discount, positive for a surcharge.', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('issued_snapshot', models.JSONField(blank=True, default=dict, editable=False)),
                ('issued_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='billing.client')),
                ('converted_from', models.ForeignKey(blank=True, editable=False, help_text='On an invoice: the quote it was generated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.document')),
                ('replaces', models.ForeignKey(blank=True, editable=False, help_text='On a reissued invoice: the cancelled one it corrects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='billing.document')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('position', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.document')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['kind', 'status'], name='billing_doc_kind_883c63_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['kind', '-number'], name='billing_doc_kind_aafb53_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['client'], name='billing_doc_client__a52158_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('kind', 'number'), name='billing_unique_number_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'quote'), ('status__in', ['draft', 'sent', 'accepted', 'declined'])), models.Q(('kind', 'invoice'), ('status__in', ['draft', 'issued', 'paid', 'cancelled'])), _connector='OR'), name='billing_status_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('number__isnull', True), ('status', 'draft')), models.Q(models.Q(('status', 'draft'), _negated=True), ('number__isnull', False)), _connector='OR'), name='billing_number_iff_issued'),
        ),
    ]
