# Generated by Django 5.2.17 on 2026-09-30 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0004_delete_image_clientalbum_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(max_length=300, unique=True)),
                ('version', models.CharField(blank=True, help_text='Cache-busting version', max_length=32)),
                ('format', models.CharField(blank=True, max_length=12)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('bytes', models.BigIntegerField(default=0)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('dominant_color', models.CharField(blank=True, help_text='Hex tint shown while the image loads', max_length=9)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this photo in the homepage carousel')),
                ('position', models.PositiveIntegerField(default=0)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='albums.clientalbum')),
            ],
            options={
                'ordering': ['position', 'original_filename'],
            },
        ),
    ]
