# Generated by Django 5.2.17 on 2026-09-30 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.gallery'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['gallery', 'position'], name='core_photo_gallery_855b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['album', 'position'], name='core_photo_album_i_aa9498_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['is_featured'], name='core_photo_is_feat_4e7233_idx'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('album__isnull', True), ('gallery__isnull', False)), models.Q(('album__isnull', False), ('gallery__isnull', True)), _connector='OR'), name='photo_belongs_to_exactly_one_owner'),
        ),
    ]
