# Generated by Django 5.2.4 on 2025-08-03 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientalbum',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='clientalbum',
            name='folder_name',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_drive_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('local_file_path', models.CharField(max_length=500)),
                ('folder_name', models.CharField(max_length=200)),
                ('parent_folder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['google_drive_id'], name='albums_imag_google__2df55b_idx'), models.Index(fields=['folder_name'], name='albums_imag_folder__d15996_idx'), models.Index(fields=['parent_folder_name'], name='albums_imag_parent__3fd8c8_idx')],
            },
        ),
    ]
