# Generated by Django 5.2.4 on 2025-08-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_title_clientalbum_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientalbum',
            name='folder_name',
            field=models.CharField(blank=True, help_text='Google Drive subfolder name', max_length=200, null=True),
        ),
    ]
