# Generated by Django 5.2.17 on 2026-09-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_clientalbum_folder_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='clientalbum',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional. After this moment the link stops working.', null=True),
        ),
        migrations.AddField(
            model_name='clientalbum',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Untick to revoke the client's link immediately"),
        ),
        migrations.AlterField(
            model_name='clientalbum',
            name='folder_name',
            field=models.CharField(blank=True, help_text='Legacy Google Drive subfolder', max_length=200, null=True),
        ),
    ]
