# Generated by Django 5.2.17 on 2026-09-30 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_delete_image_clientalbum_expires_at_and_more'),
        ('billing', '0002_seed_sequences_and_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientalbum',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Optional. Links this shoot to a billing client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='billing.client'),
        ),
    ]
