# Generated by Django 5.2.17 on 2026-09-30 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('shot_on', models.DateField(blank=True, null=True)),
                ('position', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_published', models.BooleanField(default=True, help_text="Unpublished galleries are hidden from the portfolio. Used for the hidden 'featured' gallery that feeds the homepage carousel.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ForeignKey(blank=True, help_text='Defaults to the first photo when unset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.photo')),
            ],
            options={
                'verbose_name_plural': 'galleries',
                'ordering': ['position', '-shot_on', 'title'],
            },
        ),
    ]
